name: build-deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t basavaraj1234/hotstar-app:latest .
          docker push basavaraj1234/hotstar-app:latest

      # Step 4: Configure AWS Credentials (IAM Role or User)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 5: Update kubeconfig for EKS
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name my-eks-cluster --region us-east-1

      # Step 6: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/hotstar-app hotstar-app=basavaraj1234/hotstar-app:latest
          kubectl rollout status deployment/hotstar-app
